-- Build database. Sources: community consensus for Patch 8 (2025-2026) plus our own damage models for the origin
-- characters. Every level follows the game's own progression tables (what each class level offers).
--
-- Each build:
--   classes   : every class used (for matching a character to builds)
--   start     : the class to pick at character level 1
--   races     : best first; races give features only (ability bonuses are free +2/+1)
--   bg        : the background to pick (exact menu label); background : the window text for it
--   deity     : the deity to pick (clerics only; it has no rules effect)
--   raceHl    : the race's own choices (e.g. the High Elf cantrip, the Human Versatility skill)
--   base      : point-buy values BEFORE the +2/+1 racial bonus (27 points, 8-15)
--   plus2/plus1 : where to put the racial bonuses
--   skills    : every skill proficiency after creation (class picks + background)
--   levels[n] : L(class taken at character level n, { window text }, { exact menu labels to star }, extra)
--               extra.asi  = ability raises chosen at this level ({ STR = 2 } or { WIS = 1, CON = 1 }); the menu
--                            rows get the target in brackets ("Dexterity (19, +2)"), never a star
--               extra.swap = { out = spell to replace, into = new spell } for the "replace a spell" step
-- Menu labels are the game's English texts, e.g. "Metamagic: Quickened Spell", "Agonising Blast", "Giant".

BA = BA or {}

local function L(cls, picks, hl, x)
  x = x or {}
  return { cls = cls, picks = picks, hl = hl or {}, asi = x.asi, swap = x.swap }
end

BA.Builds = {
  ---------------------------------------------------------------- PALADIN-BASED
  {
    id = "sorcadin", name = "Sorcadin (Vengeance Paladin 6 / Shadow Sorcerer 6)", tier = "S+",
    role = "Melee nova damage, party face, crit-smite lockdown",
    why = "Quickened Hold Person (paralysed = auto-crit in melee) + Extra Attack + Divine Smite with sorcerer slots. Best overall build in most Patch 8 rankings.",
    classes = { "Paladin", "Sorcerer" }, start = "Paladin",
    races = { "Half-Orc", "Githyanki", "Shield Dwarf" },
    raceWhy = "Half-Orc: Savage Attacks + Relentless Endurance double crit-smite damage. Githyanki: free Misty Step.",
    background = "Soldier (Athletics, Intimidation)", bg = "Soldier",
    base = { STR = 15, DEX = 10, CON = 14, INT = 8, WIS = 8, CHA = 15 }, plus2 = "STR", plus1 = "CHA",
    skills = { "Athletics", "Intimidation", "Persuasion", "Insight" },
    levels = {
      L("Paladin", { "Oath of Vengeance", "Skills: Persuasion, Insight", "Weapon: Greatsword / polearm" }, { "Oath of Vengeance", "Persuasion", "Insight" }),
      L("Paladin", { "Fighting Style: Great Weapon Fighting", "Prepare: Bless, Command, Shield of Faith, Cure Wounds" }, { "Great Weapon Fighting", "Bless", "Command", "Shield of Faith", "Cure Wounds" }),
      L("Paladin", { "Oath spells Bane and Hunter's Mark are always prepared", "Keep Divine Smite for crits" }, {}),
      L("Paladin", { "Feat: Great Weapon Master" }, { "Great Weapon Master" }),
      L("Paladin", { "Extra Attack", "Prepare: Aid, Magic Weapon (Hold Person and Misty Step come free with the oath)" }, { "Aid", "Magic Weapon" }),
      L("Paladin", { "Aura of Protection" }, {}),
      L("Sorcerer", { "Sorcerous Origin: Shadow Magic", "Cantrips: Booming Blade, Minor Illusion, Mage Hand, Friends", "Spells: Shield, Magic Missile" }, { "Shadow Magic", "Booming Blade", "Minor Illusion", "Mage Hand", "Friends", "Shield", "Magic Missile" }),
      L("Sorcerer", { "Metamagic: Twinned Spell, Extended Spell", "Spell: Expeditious Retreat" }, { "Metamagic: Twinned Spell", "Metamagic: Extended Spell", "Expeditious Retreat" }),
      L("Sorcerer", { "Metamagic: Quickened Spell (Quickened Hold Person)", "Spell: Mirror Image" }, { "Metamagic: Quickened Spell", "Mirror Image" }),
      L("Sorcerer", { "Feat: Ability Improvement +2 CHA", "Cantrip: Light", "Spell: Invisibility" }, { "Ability Improvement", "Light", "Invisibility" }, { asi = { CHA = 2 } }),
      L("Sorcerer", { "Spell: Haste" }, { "Haste" }),
      L("Sorcerer", { "Hound of Ill Omen", "Spell: Counterspell" }, { "Counterspell" }),
    },
    gear = "Helldusk Armour, Balduran's Giantslayer, Gauntlets of Hill Giant Strength / Helldusk Gloves, Amulet of Greater Health",
  },
  {
    id = "oathbreaker", name = "Pure Paladin 12 (Oathbreaker)", tier = "S+",
    role = "Melee burst + aura support, best dialogue presence",
    why = "Single-class Paladin got buffed in Patch 8: Aura of Hate, Improved Divine Smite at 11, heavy armour, no multiclass delays.",
    classes = { "Paladin" }, start = "Paladin",
    races = { "Half-Orc", "Githyanki", "Shield Dwarf" },
    raceWhy = "Half-Orc Savage Attacks multiplies smite crits.",
    background = "Soldier (Athletics, Intimidation)", bg = "Soldier",
    base = { STR = 15, DEX = 10, CON = 14, INT = 8, WIS = 8, CHA = 15 }, plus2 = "STR", plus1 = "CHA",
    skills = { "Athletics", "Intimidation", "Persuasion", "Insight" },
    levels = {
      L("Paladin", { "Oath of Vengeance (break it later at the Oathbreaker Knight for Oathbreaker)", "Skills: Persuasion, Insight" }, { "Oath of Vengeance", "Persuasion", "Insight" }),
      L("Paladin", { "Fighting Style: Great Weapon Fighting", "Prepare: Bless, Command, Shield of Faith, Thunderous Smite" }, { "Great Weapon Fighting", "Bless", "Command", "Shield of Faith", "Thunderous Smite" }),
      L("Paladin", { "Channel Oath unlocked" }, {}),
      L("Paladin", { "Feat: Great Weapon Master" }, { "Great Weapon Master" }),
      L("Paladin", { "Extra Attack", "Prepare: Aid, Magic Weapon" }, { "Aid", "Magic Weapon" }),
      L("Paladin", { "Aura of Protection" }, {}),
      L("Paladin", { "Aura of Hate (Oathbreaker)" }, {}),
      L("Paladin", { "Feat: Ability Improvement +2 STR" }, { "Ability Improvement" }, { asi = { STR = 2 } }),
      L("Paladin", { "Prepare: Crusader's Mantle, Revivify" }, { "Crusader's Mantle", "Revivify" }),
      L("Paladin", { "Aura of Courage" }, {}),
      L("Paladin", { "Improved Divine Smite" }, {}),
      L("Paladin", { "Feat: Savage Attacker (or Ability Improvement CHA)" }, { "Savage Attacker" }),
    },
    gear = "Helldusk Armour, Balduran's Giantslayer, Gauntlets of Hill Giant Strength, Amulet of Greater Health",
  },
  {
    id = "bardadin", name = "Bardadin (Paladin 2 / College of Swords Bard 10)", tier = "S",
    role = "Face + control + melee damage; easiest strong build",
    why = "Paladin dip gives heavy armour and Divine Smite; Swords Bard gets Extra Attack, Slashing Flourish and Magical Secrets.",
    classes = { "Paladin", "Bard" }, start = "Paladin",
    races = { "Githyanki", "Half-Elf", "Half-Orc" },
    raceWhy = "Githyanki: Misty Step + extra weapon proficiencies.",
    background = "Charlatan (Deception, Sleight of Hand)", bg = "Charlatan",
    base = { STR = 15, DEX = 10, CON = 14, INT = 8, WIS = 8, CHA = 15 }, plus2 = "CHA", plus1 = "STR",
    skills = { "Athletics", "Persuasion", "Deception", "Sleight of Hand" },
    levels = {
      L("Paladin", { "Oath of Vengeance", "Skills: Athletics, Persuasion" }, { "Oath of Vengeance", "Athletics", "Persuasion" }),
      L("Paladin", { "Fighting Style: Defence", "Prepare: Bless, Command, Shield of Faith, Wrathful Smite" }, { "Defence", "Bless", "Command", "Shield of Faith", "Wrathful Smite" }),
      L("Bard", { "Skill: Perception", "Cantrips: Vicious Mockery, Friends", "Spells: Healing Word, Dissonant Whispers, Thunderwave, Faerie Fire" }, { "Perception", "Vicious Mockery", "Friends", "Healing Word", "Dissonant Whispers", "Thunderwave", "Faerie Fire" }),
      L("Bard", { "Spell: Heroism" }, { "Heroism" }),
      L("Bard", { "College of Swords", "Fighting Style: Duelling", "Spell: Hold Person", "Expertise: Athletics, Persuasion" }, { "College of Swords", "Duelling", "Hold Person", "Athletics", "Persuasion" }),
      L("Bard", { "Feat: Ability Improvement +2 CHA", "Cantrip: Minor Illusion", "Spell: Shatter" }, { "Ability Improvement", "Minor Illusion", "Shatter" }, { asi = { CHA = 2 } }),
      L("Bard", { "Spell: Hypnotic Pattern" }, { "Hypnotic Pattern" }),
      L("Bard", { "Extra Attack", "Spell: Glyph of Warding" }, { "Glyph of Warding" }),
      L("Bard", { "Spell: Dimension Door" }, { "Dimension Door" }),
      L("Bard", { "Feat: Alert", "Spell: Greater Invisibility" }, { "Alert", "Greater Invisibility" }),
      L("Bard", { "Spell: Hold Monster" }, { "Hold Monster" }),
      L("Bard", { "Cantrip: Mage Hand", "Spell: Dominate Person", "Magical Secrets: Counterspell, Banishment", "Expertise: Deception, Perception" }, { "Mage Hand", "Dominate Person", "Counterspell", "Banishment", "Deception", "Perception" }),
    },
    gear = "Helldusk / Armour of Agility, Duellist's Prerogative (rapier), Gloves of Dexterity",
  },
  {
    id = "lockadin", name = "Lockadin (Vengeance Paladin 5 / Hexblade Warlock 7)", tier = "S",
    role = "Sustained Charisma melee, short-rest slot recovery",
    why = "Hexblade lets you attack with CHA, so CHA is your only stat; warlock slots refresh on short rest for more smites.",
    classes = { "Paladin", "Warlock" }, start = "Paladin",
    races = { "Half-Orc", "Githyanki", "Half-Elf" },
    raceWhy = "Half-Orc for crits, Githyanki for Misty Step.",
    background = "Noble (History, Persuasion)", bg = "Noble",
    base = { STR = 8, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 15 }, plus2 = "CHA", plus1 = "CON",
    skills = { "Intimidation", "Athletics", "History", "Persuasion" },
    levels = {
      L("Paladin", { "Oath of Vengeance", "Skills: Intimidation, Athletics" }, { "Oath of Vengeance", "Intimidation", "Athletics" }),
      L("Warlock", { "Patron: The Hexblade (Hex Warrior = CHA weapon attacks)", "Cantrips: Eldritch Blast, Booming Blade", "Spells: Hex, Armour of Agathys" }, { "The Hexblade", "Eldritch Blast", "Booming Blade", "Hex", "Armour of Agathys" }),
      L("Paladin", { "Fighting Style: Great Weapon Fighting (or Duelling)", "Prepare: Bless, Command, Shield of Faith, Wrathful Smite" }, { "Great Weapon Fighting", "Bless", "Command", "Shield of Faith", "Wrathful Smite" }),
      L("Paladin", { "Oath spells Bane and Hunter's Mark are always prepared" }, {}),
      L("Paladin", { "Feat: Great Weapon Master (or Ability Improvement CHA)" }, { "Great Weapon Master" }),
      L("Paladin", { "Extra Attack", "Prepare: Aid (Hold Person and Misty Step come free with the oath)" }, { "Aid" }),
      L("Warlock", { "Invocations: Agonising Blast, Devil's Sight", "Spell: Shield" }, { "Agonising Blast", "Devil's Sight", "Shield" }),
      L("Warlock", { "Pact of the Blade", "Spell: Mirror Image" }, { "Pact of the Blade", "Mirror Image" }),
      L("Warlock", { "Feat: Ability Improvement +2 CHA", "Cantrip: Mage Hand", "Spell: Darkness (with Devil's Sight)" }, { "Ability Improvement", "Mage Hand", "Darkness" }, { asi = { CHA = 2 } }),
      L("Warlock", { "Thirsting Blade comes free with Pact of the Blade", "Invocation: Repelling Blast", "Spell: Hunger of Hadar" }, { "Repelling Blast", "Hunger of Hadar" }),
      L("Warlock", { "Accursed Spectre", "Spell: Counterspell" }, { "Counterspell" }),
      L("Warlock", { "Invocation: Sculptor of Flesh (Lifedrinker needs Warlock 12)", "Spell: Dimension Door" }, { "Sculptor of Flesh", "Dimension Door" }),
    },
    gear = "Helldusk Armour, Sword of Chaos / Blackguard's Sword, Birthright (CHA hat), Band of the Mystic Scoundrel",
  },
  ---------------------------------------------------------------- BARBARIAN
  {
    id = "giants", name = "Path of Giants Barbarian 12", tier = "S",
    role = "Throwing tank, huge single-target damage, simple to play",
    why = "Patch 8 subclass: Giant's Rage size-up + Elemental Cleaver throws. Pure class keeps every Barbarian capstone.",
    classes = { "Barbarian" }, start = "Barbarian",
    races = { "Half-Orc", "Githyanki", "Shield Dwarf" },
    raceWhy = "Half-Orc: Savage Attacks on crits. Duergar: Enlarge also stacks with throws.",
    background = "Outlander (Athletics, Survival)", bg = "Outlander",
    base = { STR = 15, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 8 }, plus2 = "STR", plus1 = "CON",
    skills = { "Athletics", "Survival", "Intimidation", "Perception" },
    levels = {
      L("Barbarian", { "Skills: Intimidation, Perception", "Weapon: throwing weapons / Returning Pike" }, { "Intimidation", "Perception" }),
      L("Barbarian", { "Reckless Attack, Danger Sense" }, {}),
      L("Barbarian", { "Path of Giants" }, { "Giant" }),
      L("Barbarian", { "Feat: Tavern Brawler (+1 STR)" }, { "Tavern Brawler" }, { asi = { STR = 1 } }),
      L("Barbarian", { "Extra Attack" }, {}),
      L("Barbarian", { "Elemental Cleaver" }, {}),
      L("Barbarian", { "Feral Instinct" }, {}),
      L("Barbarian", { "Feat: Ability Improvement +2 STR" }, { "Ability Improvement" }, { asi = { STR = 2 } }),
      L("Barbarian", { "Brutal Critical" }, {}),
      L("Barbarian", { "Mighty Impel" }, {}),
      L("Barbarian", { "Relentless Rage" }, {}),
      L("Barbarian", { "Feat: Alert (or Savage Attacker)" }, { "Alert" }),
    },
    gear = "Returning Pike / Nyrulna, Gauntlets of Hill Giant Strength, Gloves of Belligerent Skies",
  },
  {
    id = "throwzerker", name = "Throwzerker (Berserker Barbarian 10 / Fighter 2)", tier = "S",
    role = "Throw everything; Frenzy bonus-action throws + Action Surge",
    why = "Tavern Brawler adds STR twice to thrown weapon hits; Frenzy gives an extra throw every turn.",
    classes = { "Barbarian", "Fighter" }, start = "Barbarian",
    races = { "Half-Orc", "Githyanki", "Duergar" },
    raceWhy = "Half-Orc for crit damage; Duergar Enlarge adds damage dice.",
    background = "Soldier (Athletics, Intimidation)", bg = "Soldier",
    base = { STR = 15, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 8 }, plus2 = "STR", plus1 = "CON",
    skills = { "Athletics", "Intimidation", "Perception", "Survival" },
    levels = {
      L("Barbarian", { "Skills: Perception, Survival" }, { "Perception", "Survival" }),
      L("Barbarian", { "Reckless Attack" }, {}),
      L("Barbarian", { "Path of the Berserker" }, { "Berserker" }),
      L("Barbarian", { "Feat: Tavern Brawler (+1 STR)" }, { "Tavern Brawler" }, { asi = { STR = 1 } }),
      L("Barbarian", { "Extra Attack" }, {}),
      L("Fighter", { "Fighting Style: Defence" }, { "Defence" }),
      L("Fighter", { "Action Surge" }, {}),
      L("Barbarian", { "Mindless Rage" }, {}),
      L("Barbarian", { "Feral Instinct" }, {}),
      L("Barbarian", { "Feat: Ability Improvement +2 STR" }, { "Ability Improvement" }, { asi = { STR = 2 } }),
      L("Barbarian", { "Brutal Critical" }, {}),
      L("Barbarian", { "Intimidating Presence" }, {}),
    },
    gear = "Returning Pike, Nyrulna, Gauntlets of Hill Giant Strength, Gloves of Belligerent Skies",
  },
  {
    id = "throw_zerk7_thief3", name = "Throwzerker Thief (Berserker 7 / Thief 3 / Fighter 2)", tier = "S+",
    role = "Thrower: 4 throws every turn, 2 of them knock Prone; Nyrulna blast on every throw",
    why = "Enraged Throw (Berserker) is a bonus action with no once-per-turn limit, and Thief's Fast Hands gives a second bonus action, so 2 throws from Extra Attack + 2 Enraged Throws every turn; each Enraged Throw knocks the target Prone. Tavern Brawler adds STR to every throw's attack and damage, Action Surge adds 2 more throws once per short rest. About 55% more sustained damage than Path of Giants 12 in Act 3 and 30% more than Berserker 10 / Fighter 2.",
    classes = { "Barbarian", "Rogue", "Fighter" }, start = "Barbarian",
    races = { "Zariel Tiefling", "Githyanki", "Duergar" },
    raceWhy = "Karlach is locked to Zariel Tiefling (fire resistance). Others: Githyanki Misty Step for throwing angles; Duergar Enlarge and Invisibility.",
    background = "Outlander (Karlach's own: Athletics, Survival)", bg = "Outlander",
    base = { STR = 15, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 8 }, plus2 = "STR", plus1 = "CON",
    skills = { "Athletics", "Survival", "Intimidation", "Perception" },
    levels = {
      L("Barbarian", { "Rage, Unarmoured Defence", "Skills: Intimidation, Perception", "Weapon: two-handed melee until Tavern Brawler" }, { "Intimidation", "Perception" }),
      L("Barbarian", { "Reckless Attack, Danger Sense" }, {}),
      L("Barbarian", { "Subclass: Berserker (Frenzy, Frenzied Strike, Enraged Throw)" }, { "Berserker" }),
      L("Barbarian", { "Feat: Tavern Brawler (+1 STR, STR 18)", "Weapon: Returning Pike (throw)" }, { "Tavern Brawler" }, { asi = { STR = 1 } }),
      L("Barbarian", { "Extra Attack, Fast Movement" }, {}),
      L("Rogue", { "Skill: Sleight of Hand", "Expertise: Athletics, Sleight of Hand" }, { "Sleight of Hand", "Athletics" }),
      L("Rogue", { "Cunning Action" }, {}),
      L("Rogue", { "Subclass: Thief (Fast Hands = second bonus action = second Enraged Throw)" }, { "Thief" }),
      L("Fighter", { "Fighting Style: Defence (+1 AC in armour)", "Second Wind" }, { "Defence" }),
      L("Fighter", { "Action Surge" }, {}),
      L("Barbarian", { "Mindless Rage" }, {}),
      L("Barbarian", { "Feral Instinct" }, {}),
    },
    gear = "Returning Pike -> Nyrulna + Viconia's Walking Fortress, Ring of Flinging, Gloves of Uninhibited Kushigo, Caustic Band, Horns of the Berserker, Armour of Agility or Bonespike Garb (never Helldusk Armour), Elixir of Cloud Giant Strength",
    note = "Respec Karlach with Withers (she stays a Zariel Tiefling). No heavy body armour: Helldusk Armour is Plate and switches off Rage damage, throw bonus and resistances. Nyrulna's 3d4 blast also hits allies and Karlach within 6 m of the target: throw from further away.",
  },
  {
    id = "throw_zerk5_thief4", name = "Throw-Thief (Berserker Barbarian 5 / Thief Rogue 4 / Champion Fighter 3)", tier = "S+",
    role = "Thrower: 4 Tavern Brawler throws a turn, two of them Enraged Throws that knock the target Prone",
    why = "Enraged Throw is a bonus action with no once-per-turn limit, so Thief's Fast Hands gives a second one every turn; each Enraged Throw adds STR again and knocks Prone (no save), so the other throws get Advantage within 3 m. Tavern Brawler adds STR to every throw's attack and damage. With Bhaalist Armour (Murder Tribunal) Nyrulna's piercing damage is doubled: about 37% more sustained damage than the Throwzerker 10/2.",
    classes = { "Barbarian", "Rogue", "Fighter" }, start = "Barbarian",
    races = { "Duergar", "Half-Orc", "Githyanki" },
    raceWhy = "Duergar: Enlarge (+1d4 weapon damage for one fight a day) and Advantage against Hold Person / charm. Half-Orc: Relentless Endurance and 9 m speed. Githyanki: Misty Step. Savage Attacks does not work on throws.",
    background = "Haunted One (fixed for the Dark Urge: Intimidation, Medicine)", bg = "Haunted One",
    base = { STR = 15, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 8 }, plus2 = "STR", plus1 = "CON",
    skills = { "Athletics", "Perception", "Intimidation", "Medicine" },
    levels = {
      L("Barbarian", { "Skills: Athletics, Perception (Haunted One already gives Intimidation, Medicine)", "Weapon: Returning Pike / any thrown weapon" }, { "Athletics", "Perception" }),
      L("Barbarian", { "Reckless Attack, Danger Sense" }, {}),
      L("Barbarian", { "Subclass: Berserker (Frenzy -> Enraged Throw, a bonus-action throw that knocks Prone)" }, { "Berserker" }),
      L("Barbarian", { "Feat: Tavern Brawler (+1 STR)" }, { "Tavern Brawler" }, { asi = { STR = 1 } }),
      L("Barbarian", { "Extra Attack (works with the Throw action)" }, {}),
      L("Rogue", { "Skill: Sleight of Hand", "Expertise: Sleight of Hand, Athletics (Nyrulna's chest is Sleight of Hand DC 20)" }, { "Sleight of Hand", "Athletics" }),
      L("Rogue", { "Cunning Action" }, {}),
      L("Rogue", { "Subclass: Thief (Fast Hands = a second bonus action = a second Enraged Throw)" }, { "Thief" }),
      L("Fighter", { "Fighting Style: Defence" }, { "Defence" }),
      L("Fighter", { "Action Surge" }, {}),
      L("Fighter", { "Subclass: Champion (Improved Critical: crit on 19)" }, { "Champion" }),
      L("Rogue", { "Feat: Ability Improvement +2 STR (20) (or Dexterity instead with an Elixir of Cloud Giant Strength running all the time)" }, { "Ability Improvement" }, { asi = { STR = 2 } }),
    },
    gear = "Returning Pike -> Nyrulna, Gloves of Uninhibited Kushigo, Ring of Flinging, Caustic Band, Bhaalist Armour, Helmet of Grit / Sarevok's Horned Helmet, Elixir of Cloud Giant Strength",
    note = "Rage first (bonus action), then Enraged Throw with the Fast Hands bonus action so the target is Prone before the normal throws. Stand within 3 m of the target: Prone advantage and the Bhaalist aura both stop at 3 m. Only 3 rages per long rest (Barbarian 5).",
  },
  ---------------------------------------------------------------- MONK
  {
    id = "tbmonk", name = "Tavern Brawler Open Hand Monk 12", tier = "S",
    role = "Fastest striker in the game; stun-lock with Stunning Strike",
    why = "Tavern Brawler adds STR to unarmed attack AND damage again; Flurry gives up to 4-5 hits a turn.",
    classes = { "Monk" }, start = "Monk",
    races = { "Wood Elf", "Wood Half-Elf", "Githyanki" },
    raceWhy = "Wood Elf/Half-Elf: extra movement + Stealth. Githyanki: Misty Step.",
    background = "Folk Hero (Animal Handling, Survival)", bg = "Folk Hero",
    base = { STR = 15, DEX = 15, CON = 14, INT = 8, WIS = 10, CHA = 8 }, plus2 = "STR", plus1 = "DEX",
    skills = { "Athletics", "Acrobatics", "Animal Handling", "Survival" },
    levels = {
      L("Monk", { "Skills: Athletics, Acrobatics", "Fight unarmed" }, { "Athletics", "Acrobatics" }),
      L("Monk", { "Ki: Flurry of Blows, Patient Defence, Step of the Wind" }, {}),
      L("Monk", { "Way of the Open Hand" }, { "Way of the Open Hand" }),
      L("Monk", { "Feat: Tavern Brawler (+1 STR)" }, { "Tavern Brawler" }, { asi = { STR = 1 } }),
      L("Monk", { "Extra Attack, Stunning Strike" }, {}),
      L("Monk", { "Ki-Empowered Strikes, Manifestation of Body/Mind" }, {}),
      L("Monk", { "Evasion, Stillness of Mind" }, {}),
      L("Monk", { "Feat: Ability Improvement +2 STR" }, { "Ability Improvement" }, { asi = { STR = 2 } }),
      L("Monk", { "Advanced Unarmoured Movement" }, {}),
      L("Monk", { "Purity of Body" }, {}),
      L("Monk", { "Quivering Palm" }, {}),
      L("Monk", { "Feat: Ability Improvement +2 DEX (or WIS)" }, { "Ability Improvement" }, { asi = { DEX = 2 } }),
    },
    gear = "Gloves of Soul Catching, Bracers of Defence, Vest of Soul Rejuvenation",
  },
  ---------------------------------------------------------------- FIGHTER
  {
    id = "bmgiant", name = "Battle Master Fighter 12 (Giantslayer + advantage)", tier = "S+",
    role = "Melee damage: 3 attacks + Action Surge, Trip/Riposte, best burst and trash clearing",
    why = "Act 3 boss fights: 110 damage a round with an advantage source (Gloves of the Automaton + Hill Giant elixir), 136 with the Risky Ring, 152 when hasted; best Act 2, best burst and fastest trash clearing. Great Weapon Master pays only with Advantage: switch 'All In' off without it.",
    classes = { "Fighter" }, start = "Fighter",
    races = { "Githyanki", "Half-Orc", "Shield Dwarf" },
    raceWhy = "Githyanki (Lae'zel, locked): Misty Step, Astral Knowledge; Githyanki Greatsword / Silver Sword psychic bonus. Half-Orc for a Tav: Savage Attacks on crits.",
    background = "Soldier (Lae'zel's own: Athletics, Intimidation)", bg = "Soldier",
    base = { STR = 15, DEX = 10, CON = 15, INT = 8, WIS = 14, CHA = 8 }, plus2 = "STR", plus1 = "CON",
    skills = { "Athletics", "Intimidation", "Perception", "Insight" },
    levels = {
      L("Fighter", { "Fighting Style: Great Weapon Fighting", "Skills: Perception, Insight (Athletics + Intimidation come from Soldier)" }, { "Great Weapon Fighting", "Perception", "Insight" }),
      L("Fighter", { "Action Surge" }, {}),
      L("Fighter", { "Battle Master", "Manoeuvres: Trip Attack, Riposte, Precision Attack" }, { "Battle Master", "Trip Attack", "Riposte", "Precision Attack" }),
      L("Fighter", { "Feat: Great Weapon Master (toggle 'Great Weapon Master: All In' off when you have no Advantage)" }, { "Great Weapon Master" }),
      L("Fighter", { "Extra Attack" }, {}),
      L("Fighter", { "Feat: Ability Improvement +2 STR (19)" }, { "Ability Improvement" }, { asi = { STR = 2 } }),
      L("Fighter", { "Manoeuvres: Menacing Attack, Goading Attack (5th superiority die)" }, { "Menacing Attack", "Goading Attack" }),
      L("Fighter", { "Feat: Savage Attacker" }, { "Savage Attacker" }),
      L("Fighter", { "Indomitable" }, {}),
      L("Fighter", { "Improved Combat Superiority (d10)", "Manoeuvres: Pushing Attack, Disarming Attack" }, { "Pushing Attack", "Disarming Attack" }),
      L("Fighter", { "Improved Extra Attack (3 attacks)" }, {}),
      L("Fighter", { "Feat: Alert" }, { "Alert" }),
    },
    gear = "Balduran's Giantslayer, Helldusk Armour, Helm of Balduran, Gloves of the Automaton + Elixir of Hill Giant Strength (or Risky Ring + Gauntlets of Hill Giant Strength), Cloak of Displacement, Amulet of Greater Health",
    note = "Lae'zel is already a Fighter: no respec needed (redo her levels with Withers if she was levelled otherwise). Open every boss fight with Action Surge; Trip Attack on the first swing each round; keep 1 die for Riposte. Give her an advantage source - it is worth more than +2 STR.",
  },
  {
    id = "battlemaster", name = "Battle Master Fighter 12", tier = "S",
    role = "Reliable melee; 3 attacks + Action Surge + manoeuvres",
    why = "Most feats of any class, third attack at 11, superiority dice for control.",
    classes = { "Fighter" }, start = "Fighter",
    races = { "Half-Orc", "Githyanki", "Shield Dwarf" },
    raceWhy = "Half-Orc crits; Githyanki Misty Step + Astral Knowledge.",
    background = "Soldier (Athletics, Intimidation)", bg = "Soldier",
    base = { STR = 15, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 8 }, plus2 = "STR", plus1 = "CON",
    skills = { "Athletics", "Intimidation", "Perception", "Survival" },
    levels = {
      L("Fighter", { "Fighting Style: Great Weapon Fighting", "Skills: Perception, Survival" }, { "Great Weapon Fighting", "Perception", "Survival" }),
      L("Fighter", { "Action Surge" }, {}),
      L("Fighter", { "Battle Master", "Manoeuvres: Precision Attack, Trip Attack, Menacing Attack" }, { "Battle Master", "Precision Attack", "Trip Attack", "Menacing Attack" }),
      L("Fighter", { "Feat: Great Weapon Master" }, { "Great Weapon Master" }),
      L("Fighter", { "Extra Attack" }, {}),
      L("Fighter", { "Feat: Ability Improvement +2 STR" }, { "Ability Improvement" }, { asi = { STR = 2 } }),
      L("Fighter", { "Manoeuvres: Riposte, Pushing Attack" }, { "Riposte", "Pushing Attack" }),
      L("Fighter", { "Feat: Alert" }, { "Alert" }),
      L("Fighter", { "Indomitable" }, {}),
      L("Fighter", { "Manoeuvres: Disarming Attack, Goading Attack" }, { "Disarming Attack", "Goading Attack" }),
      L("Fighter", { "Two Extra Attacks" }, {}),
      L("Fighter", { "Feat: Savage Attacker (or Ability Improvement)" }, { "Savage Attacker" }),
    },
    gear = "Balduran's Giantslayer, Helldusk Armour, Gauntlets of Hill Giant Strength, Amulet of Greater Health",
  },
  ---------------------------------------------------------------- RANGER / ROGUE
  {
    id = "gloomassassin", name = "Gloom Stalker 5 / Assassin 4 / Battle Master 3", tier = "S",
    role = "Archer: massive first-round alpha strike, extra actions",
    why = "Gloom Stalker's Dread Ambusher + Assassin auto-crits on surprised targets + Action Surge = enemies die before acting.",
    classes = { "Ranger", "Rogue", "Fighter" }, start = "Ranger",
    races = { "Wood Half-Elf", "Lightfoot Halfling", "Deep Gnome" },
    raceWhy = "Wood Half-Elf: speed + Stealth. Halfling: Lucky.",
    background = "Urchin (Sleight of Hand, Stealth)", bg = "Urchin",
    base = { STR = 8, DEX = 15, CON = 15, INT = 10, WIS = 14, CHA = 8 }, plus2 = "DEX", plus1 = "CON",
    skills = { "Stealth", "Sleight of Hand", "Perception", "Insight", "Survival" },
    levels = {
      L("Ranger", { "Favoured Enemy: Bounty Hunter", "Natural Explorer: Beast Tamer", "Skills: Perception, Insight, Survival" }, { "Bounty Hunter", "Beast Tamer", "Perception", "Insight", "Survival" }),
      L("Ranger", { "Fighting Style: Archery", "Spells: Hunter's Mark, Ensnaring Strike" }, { "Archery", "Hunter's Mark", "Ensnaring Strike" }),
      L("Ranger", { "Gloom Stalker", "Spell: Hail of Thorns" }, { "Gloom Stalker", "Hail of Thorns" }),
      L("Ranger", { "Feat: Sharpshooter" }, { "Sharpshooter" }),
      L("Ranger", { "Extra Attack", "Spell: Pass Without Trace" }, { "Pass Without Trace" }),
      L("Rogue", { "Skill: Acrobatics", "Expertise: Stealth, Perception" }, { "Acrobatics", "Stealth", "Perception" }),
      L("Rogue", { "Cunning Action" }, {}),
      L("Rogue", { "Assassin" }, { "Assassin" }),
      L("Rogue", { "Feat: Alert" }, { "Alert" }),
      L("Fighter", { "Fighting Style: Defence" }, { "Defence" }),
      L("Fighter", { "Action Surge" }, {}),
      L("Fighter", { "Battle Master", "Manoeuvres: Precision Attack, Menacing Attack, Trip Attack" }, { "Battle Master", "Precision Attack", "Menacing Attack", "Trip Attack" }),
    },
    gear = "Titanstring Bow / Gontr Mael, Gloves of Archery / Legacy of the Masters, Killer's Sweetheart, Strange Conduit Ring",
    note = "Starting as Rogue instead (for extra skills/expertise) works too - just follow the same levels in any order after Ranger 5.",
  },
  {
    id = "thx", name = "Gloom Stalker 5 / Battle Master 3 / Thief 4 (dual hand crossbows)", tier = "S+",
    role = "Ranged: 4 hand-crossbow shots every turn, best sustained damage",
    why = "Thief's Fast Hands = a second bonus action; each bonus action fires the off-hand hand crossbow. Sharpshooter and Archery also apply to off-hand ranged shots, Two-Weapon Fighting adds DEX to them. About 60% more sustained damage than the longbow Assassin version.",
    classes = { "Ranger", "Fighter", "Rogue" }, start = "Ranger",
    races = { "Wood Half-Elf", "Lightfoot Halfling", "Deep Gnome" },
    raceWhy = "Wood Half-Elf: speed + Stealth. Halfling: Lucky.",
    background = "Urchin (Sleight of Hand, Stealth)", bg = "Urchin",
    base = { STR = 8, DEX = 15, CON = 15, INT = 10, WIS = 14, CHA = 8 }, plus2 = "DEX", plus1 = "CON",
    skills = { "Stealth", "Sleight of Hand", "Perception", "Insight", "Survival" },
    levels = {
      L("Ranger", { "Favoured Enemy: Bounty Hunter", "Natural Explorer: Beast Tamer", "Skills: Perception, Insight, Survival" }, { "Bounty Hunter", "Beast Tamer", "Perception", "Insight", "Survival" }),
      L("Ranger", { "Fighting Style: Archery", "Spells: Hunter's Mark, Ensnaring Strike" }, { "Archery", "Hunter's Mark", "Ensnaring Strike" }),
      L("Ranger", { "Gloom Stalker", "Spell: Hail of Thorns" }, { "Gloom Stalker", "Hail of Thorns" }),
      L("Ranger", { "Feat: Sharpshooter" }, { "Sharpshooter" }),
      L("Ranger", { "Extra Attack", "Spell: Pass Without Trace" }, { "Pass Without Trace" }),
      L("Fighter", { "Fighting Style: Two-Weapon Fighting (adds DEX to off-hand hand-crossbow damage)" }, { "Two-Weapon Fighting" }),
      L("Fighter", { "Action Surge" }, {}),
      L("Fighter", { "Battle Master", "Manoeuvres: Precision Attack, Menacing Attack, Trip Attack" }, { "Battle Master", "Precision Attack", "Menacing Attack", "Trip Attack" }),
      L("Rogue", { "Skill: Acrobatics", "Expertise: Stealth, Perception" }, { "Acrobatics", "Stealth", "Perception" }),
      L("Rogue", { "Cunning Action" }, {}),
      L("Rogue", { "Thief (Fast Hands = extra bonus action)" }, { "Thief" }),
      L("Rogue", { "Feat: Ability Improvement +2 DEX (or Alert)" }, { "Ability Improvement" }, { asi = { DEX = 2 } }),
    },
    gear = "Hand Crossbow +2 x2 / Hellfire Hand Crossbow, Gloves of Archery / Legacy of the Masters, Risky Ring, Killer's Sweetheart",
    note = "Respec Astarion with Withers to start as Ranger. Dual-wield two hand crossbows; fire the off-hand one with every bonus action.",
  },
  ---------------------------------------------------------------- CLERIC
  {
    id = "lightquick", name = "Light Domain Cleric 9 / Sorcerer 3 (Quickened)", tier = "S",
    role = "Radiant AoE caster + support: Radiance of the Dawn, Spirit Guardians and a quickened second spell",
    why = "Same as Light Cleric 12 up to level 9 (best cleric in Acts 1-2). Sorcerer 3 adds Quickened Spell: a second levelled spell each turn (Fireball, Destructive Wave, Spirit Guardians) plus Shield. The game offers Quickened Spell from Sorcerer 3, so the split is Cleric 9 / Sorcerer 3; it costs Divine Intervention, Heal / Heroes' Feast and the level-12 feat.",
    classes = { "Cleric", "Sorcerer" }, start = "Cleric",
    races = { "High Half-Elf", "Wood Half-Elf", "Githyanki" },
    raceWhy = "Shadowheart is locked High Half-Elf (spears, glaives, shields; take Mage Hand as the race cantrip). For a Tav: Wood Half-Elf speed or Githyanki Misty Step.",
    background = "Acolyte (Shadowheart's own; Insight, Religion)", bg = "Acolyte", deity = "Lathander",
    raceHl = { "Mage Hand" },
    base = { STR = 8, DEX = 14, CON = 15, INT = 8, WIS = 15, CHA = 10 }, plus2 = "WIS", plus1 = "CON",
    skills = { "Insight", "Religion", "Medicine", "Persuasion" },
    levels = {
      L("Cleric", { "Light Domain (Warding Flare; Light, Burning Hands, Faerie Fire always prepared)", "Cantrips: Guidance, Sacred Flame, Toll the Dead", "Skills: Medicine, Persuasion", "Prepare: Bless, Healing Word, Guiding Bolt, Shield of Faith" }, { "Light Domain", "Guidance", "Sacred Flame", "Toll the Dead", "Medicine", "Persuasion", "Bless", "Healing Word", "Guiding Bolt", "Shield of Faith" }),
      L("Cleric", { "Channel Divinity: Radiance of the Dawn (1 charge per short rest)" }, {}),
      L("Cleric", { "Prepare: Spiritual Weapon, Aid, Silence (domain: Flaming Sphere, Scorching Ray)" }, { "Spiritual Weapon", "Aid", "Silence" }),
      L("Cleric", { "Feat: Ability Improvement +2 WIS", "Cantrip: Bursting Sinew (Light is already granted at level 1)" }, { "Ability Improvement", "Bursting Sinew" }, { asi = { WIS = 2 } }),
      L("Cleric", { "Prepare: Spirit Guardians, Revivify, Mass Healing Word (domain: Fireball, Daylight)" }, { "Spirit Guardians", "Revivify", "Mass Healing Word" }),
      L("Cleric", { "Improved Warding Flare; 2nd Channel Divinity charge" }, {}),
      L("Cleric", { "Prepare: Banishment, Death Ward, Freedom of Movement (domain: Guardian of Faith, Wall of Fire)" }, { "Banishment", "Death Ward", "Freedom of Movement" }),
      L("Cleric", { "Potent Spellcasting (cantrips + WIS)", "Feat: Resilient - Constitution (or Ability Improvement +1 WIS +1 CON without Auntie Ethel's Hair)" }, { "Resilient", "Resilient: Constitution" }),
      L("Cleric", { "Prepare: Greater Restoration, Mass Cure Wounds (domain: Flame Strike, Destructive Wave)" }, { "Greater Restoration", "Mass Cure Wounds" }),
      L("Sorcerer", { "Sorcerous Origin: Shadow Magic (Strength of the Grave)", "Cantrips: Minor Illusion, Blade Ward, Friends, Dancing Lights", "Spells: Shield, Magic Missile" }, { "Shadow Magic", "Minor Illusion", "Blade Ward", "Friends", "Dancing Lights", "Shield", "Magic Missile" }),
      L("Sorcerer", { "Metamagic: Twinned Spell, Extended Spell", "Spell: Feather Fall" }, { "Metamagic: Twinned Spell", "Metamagic: Extended Spell", "Feather Fall" }),
      L("Sorcerer", { "Metamagic: Quickened Spell", "Spell: Misty Step", "Turn spare level-1 slots into sorcery points (Quickened = 3 points)" }, { "Metamagic: Quickened Spell", "Misty Step" }),
    },
    gear = "Markoheshkir or Staff of Spell Power, Viconia's Walking Fortress, Amulet of the Devout, Hood of the Weave / Helm of Balduran, Coruscation Ring + Callous Glow Ring, Luminous Gloves / Helldusk Gloves, Helldusk Armour / Dark Justiciar Half-Plate",
    note = "Respec with Withers (race stays High Half-Elf). Play it as Light Cleric 12 until level 9. Radiance of the Dawn cannot be quickened (no Spell flag); quicken Fireball, Destructive Wave or Spirit Guardians. Keep a light on Shadowheart (Light / Dancing Lights) for Coruscation Ring. Same build on the Shar and Selune paths.",
  },
  {
    id = "lightcleric", name = "Light Domain Cleric 12", tier = "S",
    role = "Support/healer that also nukes: Spirit Guardians + Radiating Orb",
    why = "Warding Flare protects the party; Radiance of the Dawn and Spirit Guardians with Radiating Orb gear shred groups.",
    classes = { "Cleric" }, start = "Cleric",
    races = { "Wood Half-Elf", "Shield Dwarf", "Githyanki" },
    raceWhy = "Medium armour races are wasted on clerics; pick mobility (Wood Half-Elf) or Githyanki.",
    background = "Acolyte (Insight, Religion)", bg = "Acolyte", deity = "Lathander",
    base = { STR = 8, DEX = 14, CON = 15, INT = 8, WIS = 15, CHA = 10 }, plus2 = "WIS", plus1 = "CON",
    skills = { "Insight", "Religion", "Medicine", "Persuasion" },
    levels = {
      L("Cleric", { "Light Domain", "Cantrips: Guidance, Sacred Flame, Toll the Dead", "Skills: Medicine, Persuasion", "Prepare: Bless, Healing Word, Guiding Bolt, Shield of Faith" }, { "Light Domain", "Guidance", "Sacred Flame", "Toll the Dead", "Medicine", "Persuasion", "Bless", "Healing Word", "Guiding Bolt", "Shield of Faith" }),
      L("Cleric", { "Channel Divinity: Radiance of the Dawn" }, {}),
      L("Cleric", { "Prepare: Spiritual Weapon, Aid, Silence" }, { "Spiritual Weapon", "Aid", "Silence" }),
      L("Cleric", { "Feat: Ability Improvement +2 WIS", "Cantrip: Bursting Sinew (Light is already granted)" }, { "Ability Improvement", "Bursting Sinew" }, { asi = { WIS = 2 } }),
      L("Cleric", { "Prepare: Spirit Guardians, Revivify, Mass Healing Word" }, { "Spirit Guardians", "Revivify", "Mass Healing Word" }),
      L("Cleric", { "Improved Warding Flare" }, {}),
      L("Cleric", { "Prepare: Banishment, Death Ward, Freedom of Movement" }, { "Banishment", "Death Ward", "Freedom of Movement" }),
      L("Cleric", { "Feat: War Caster (or Alert)" }, { "War Caster" }),
      L("Cleric", { "Prepare: Greater Restoration, Mass Cure Wounds (Flame Strike is a domain spell)" }, { "Greater Restoration", "Mass Cure Wounds" }),
      L("Cleric", { "Divine Intervention", "Cantrip: Resistance" }, { "Resistance" }),
      L("Cleric", { "Prepare: Heal, Blade Barrier" }, { "Heal", "Blade Barrier" }),
      L("Cleric", { "Feat: Ability Improvement +1 WIS +1 CON (or Alert)" }, { "Ability Improvement" }, { asi = { WIS = 1, CON = 1 } }),
    },
    gear = "Coruscation Ring, Spineshudder Amulet and other Radiating Orb gear",
  },
  ---------------------------------------------------------------- SORCERER / WARLOCK / WIZARD
  {
    id = "tempestevoker", name = "Evocation Wizard 10 / Tempest Cleric 2", tier = "S",
    role = "AoE lightning nuker in heavy armour; Sculpt Spells keeps allies safe",
    why = "Destructive Wrath maximises a whole Lightning cast (Markoheshkir's free Chain Lightning every short rest: about 89 per target) and Empowered Evocation adds INT to every target, dart and beam. Tempest also gives heavy armour. About 17% more sustained AoE and 24% more single-target damage than Evocation Wizard 12 at level 12, AC 22 instead of 16.",
    classes = { "Wizard", "Cleric" }, start = "Wizard",
    races = { "Human", "Githyanki", "High Elf" },
    raceWhy = "Gale is a locked Human (light armour + shields). For a Tav: Githyanki for Misty Step, High Elf for an extra wizard cantrip; Tempest gives the heavy armour anyway.",
    background = "Sage (Gale's own)", bg = "Sage", deity = "Talos",
    raceHl = { "Perception" },
    base = { STR = 8, DEX = 14, CON = 15, INT = 15, WIS = 10, CHA = 8 }, plus2 = "INT", plus1 = "CON",
    skills = { "Arcana", "History", "Investigation", "Insight", "Perception" },
    levels = {
      L("Wizard", { "Cantrips: Fire Bolt, Shocking Grasp, Minor Illusion", "Spells: Magic Missile, Shield, Chromatic Orb, Mage Armour, Find Familiar, Sleep", "Skills: Investigation, Insight (Human Versatility: Perception)" }, { "Fire Bolt", "Shocking Grasp", "Minor Illusion", "Magic Missile", "Shield", "Chromatic Orb", "Mage Armour", "Find Familiar", "Sleep", "Investigation", "Insight" }),
      L("Wizard", { "Evocation School (Sculpt Spells)", "Spells: Thunderwave, Feather Fall" }, { "Evocation", "Thunderwave", "Feather Fall" }),
      L("Wizard", { "Spells: Misty Step, Scorching Ray" }, { "Misty Step", "Scorching Ray" }),
      L("Wizard", { "Feat: Ability Improvement +2 INT", "Cantrip: Mage Hand", "Spells: Shatter, Hold Person" }, { "Ability Improvement", "Mage Hand", "Shatter", "Hold Person" }, { asi = { INT = 2 } }),
      L("Wizard", { "Spells: Fireball, Lightning Bolt (learn Haste / Counterspell from scrolls)" }, { "Fireball", "Lightning Bolt" }),
      L("Cleric", { "Tempest Domain: heavy armour + martial weapons, Wrath of the Storm, Thunderwave + Fog Cloud always prepared", "Deity: Talos", "Cantrips: Guidance, Resistance, Light", "Prepare: Bless", "Put on heavy armour (Plate Armour) now" }, { "Tempest Domain", "Guidance", "Resistance", "Light", "Bless" }),
      L("Cleric", { "Channel Divinity: Destructive Wrath (save it for Lightning Bolt / Chain Lightning on a group)", "Prepare: Healing Word" }, { "Healing Word" }),
      L("Wizard", { "Potent Cantrip", "Spells: Haste, Counterspell" }, { "Haste", "Counterspell" }),
      L("Wizard", { "Spells: Greater Invisibility, Wall of Fire" }, { "Greater Invisibility", "Wall of Fire" }),
      L("Wizard", { "Feat: Ability Improvement +1 INT +1 CON (INT 20)", "Spells: Ice Storm, Banishment" }, { "Ability Improvement", "Ice Storm", "Banishment" }, { asi = { INT = 1, CON = 1 } }),
      L("Wizard", { "Spells: Cone of Cold, Hold Monster" }, { "Cone of Cold", "Hold Monster" }),
      L("Wizard", { "Empowered Evocation", "Cantrip: Ray of Frost", "Spells: Telekinesis, Conjure Elemental" }, { "Ray of Frost", "Telekinesis", "Conjure Elemental" }),
    },
    gear = "Markoheshkir (Kereska's Favour: Lightning), Ketheric's Shield, Hood of the Weave, Armour of Persistence, Cloak of the Weave, Helldusk Gloves, Helldusk Boots, Amulet of Greater Health, Ring of Feywild Sparks, Callous Glow Ring, Elixir of Battlemage's Power",
    note = "Respec Gale once with Withers for these stats and spells; at level 6 take Cleric in the normal level-up (Fireball first at 5). Use Destructive Wrath on Markoheshkir's free Chain Lightning each short rest. Switch Kereska's Favour to Fire for single-boss fights. Amulet of the Devout gives a 4th Destructive Wrath if Shadowheart does not take it.",
  },
  {
    id = "stormsorc", name = "Storm Sorcerer 10 / Tempest Cleric 2", tier = "S",
    role = "Lightning nuker with heavy armour",
    why = "Tempest's Destructive Wrath maximises lightning/thunder damage; Tempest also grants heavy armour.",
    classes = { "Sorcerer", "Cleric" }, start = "Sorcerer",
    races = { "Githyanki", "Half-Elf", "Duergar" },
    raceWhy = "Githyanki: Misty Step; all fine since Tempest gives armour.",
    background = "Sage (Arcana, History)", bg = "Sage", deity = "Talos",
    base = { STR = 8, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 15 }, plus2 = "CHA", plus1 = "CON",
    skills = { "Arcana", "History", "Persuasion", "Deception" },
    levels = {
      L("Sorcerer", { "Storm Sorcery (start Sorcerer for CON saves)", "Cantrips: Shocking Grasp, Fire Bolt, Light, Minor Illusion", "Spells: Witch Bolt, Shield", "Skills: Persuasion, Deception" }, { "Storm Sorcery", "Shocking Grasp", "Fire Bolt", "Light", "Minor Illusion", "Witch Bolt", "Shield", "Persuasion", "Deception" }),
      L("Cleric", { "Tempest Domain (heavy armour)", "Deity: Talos", "Cantrips: Guidance, Resistance, Thaumaturgy", "Prepare: Healing Word, Bless" }, { "Tempest Domain", "Guidance", "Resistance", "Thaumaturgy", "Healing Word", "Bless" }),
      L("Cleric", { "Channel Divinity: Destructive Wrath" }, {}),
      L("Sorcerer", { "Metamagic: Twinned Spell, Distant Spell", "Spell: Chromatic Orb" }, { "Metamagic: Twinned Spell", "Metamagic: Distant Spell", "Chromatic Orb" }),
      L("Sorcerer", { "Metamagic: Quickened Spell", "Spell: Misty Step" }, { "Metamagic: Quickened Spell", "Misty Step" }),
      L("Sorcerer", { "Feat: Ability Improvement +2 CHA", "Cantrip: Mage Hand", "Spell: Hold Person" }, { "Ability Improvement", "Mage Hand", "Hold Person" }, { asi = { CHA = 2 } }),
      L("Sorcerer", { "Spell: Lightning Bolt", "Replace a spell: Witch Bolt -> Counterspell" }, { "Lightning Bolt" }, { swap = { out = "Witch Bolt", into = "Counterspell" } }),
      L("Sorcerer", { "Heart of the Storm", "Spell: Haste" }, { "Haste" }),
      L("Sorcerer", { "Spell: Greater Invisibility" }, { "Greater Invisibility" }),
      L("Sorcerer", { "Feat: War Caster (or Elemental Adept: Lightning)", "Spell: Ice Storm" }, { "War Caster", "Ice Storm" }),
      L("Sorcerer", { "Spell: Cone of Cold" }, { "Cone of Cold" }),
      L("Sorcerer", { "Metamagic: Heightened Spell", "Cantrip: Friends", "Spell: Telekinesis", "Storm's Fury follows at Sorcerer 11" }, { "Metamagic: Heightened Spell", "Friends", "Telekinesis" }),
    },
    gear = "Markoheshkir, Gloves of Belligerent Skies, Ring of Spiteful Thunder, Hat of Storm Scion's Power",
  },
  {
    id = "sorlock", name = "Sorlock (Fiend Warlock 2 / Draconic Sorcerer 10)", tier = "A",
    role = "Eldritch Blast machine gun with Quickened spell",
    why = "Agonising + Repelling Blast from a 2-level dip; Quickened Eldritch Blast (from Sorcerer 3) = two blasts a turn.",
    classes = { "Warlock", "Sorcerer" }, start = "Warlock",
    races = { "Githyanki", "Half-Elf", "Tiefling" },
    raceWhy = "Any; Githyanki for Misty Step.",
    background = "Noble (History, Persuasion)", bg = "Noble",
    base = { STR = 8, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 15 }, plus2 = "CHA", plus1 = "CON",
    skills = { "History", "Persuasion", "Deception", "Intimidation" },
    levels = {
      L("Warlock", { "Patron: The Fiend", "Cantrips: Eldritch Blast, Mage Hand", "Spells: Hex, Armour of Agathys", "Skills: Deception, Intimidation" }, { "The Fiend", "Eldritch Blast", "Mage Hand", "Hex", "Armour of Agathys", "Deception", "Intimidation" }),
      L("Warlock", { "Invocations: Agonising Blast, Repelling Blast", "Spell: Hellish Rebuke" }, { "Agonising Blast", "Repelling Blast", "Hellish Rebuke" }),
      L("Sorcerer", { "Draconic Bloodline", "Draconic Ancestry: Red (Fire)", "Cantrips: Fire Bolt, Shocking Grasp, Light, Minor Illusion", "Spells: Shield, Magic Missile" }, { "Draconic Bloodline", "Draconic Ancestry: Red (Fire)", "Fire Bolt", "Shocking Grasp", "Light", "Minor Illusion", "Shield", "Magic Missile" }),
      L("Sorcerer", { "Metamagic: Twinned Spell, Distant Spell (Quickened comes at Sorcerer 3)", "Spell: Sleep" }, { "Metamagic: Twinned Spell", "Metamagic: Distant Spell", "Sleep" }),
      L("Sorcerer", { "Metamagic: Quickened Spell (Quickened Eldritch Blast)", "Spell: Misty Step" }, { "Metamagic: Quickened Spell", "Misty Step" }),
      L("Sorcerer", { "Feat: Ability Improvement +2 CHA", "Cantrip: Friends", "Spell: Hold Person" }, { "Ability Improvement", "Friends", "Hold Person" }, { asi = { CHA = 2 } }),
      L("Sorcerer", { "Spell: Haste" }, { "Haste" }),
      L("Sorcerer", { "Elemental Affinity", "Spell: Fireball" }, { "Fireball" }),
      L("Sorcerer", { "Spell: Greater Invisibility", "Replace a spell: Sleep -> Counterspell" }, { "Greater Invisibility" }, { swap = { out = "Sleep", into = "Counterspell" } }),
      L("Sorcerer", { "Feat: Spell Sniper (cantrip: Ray of Frost)", "Spell: Wall of Fire" }, { "Spell Sniper", "Ray of Frost", "Wall of Fire" }),
      L("Sorcerer", { "Spell: Hold Monster" }, { "Hold Monster" }),
      L("Sorcerer", { "Metamagic: Heightened Spell", "Cantrip: Blade Ward", "Spell: Cone of Cold" }, { "Metamagic: Heightened Spell", "Blade Ward", "Cone of Cold" }),
    },
    gear = "Potent Robe, Birthright / Hat of Fire Acuity, Markoheshkir, Callous Glow Ring",
  },
  {
    id = "hexsorlock", name = "Hexblade Sorlock (Hexblade Warlock 2 / Draconic Sorcerer 8 / Fighter 2)", tier = "S",
    role = "Ranged Eldritch Blast damage: up to 9 beams in an Action Surge turn, Hold Person / Haste / Fireball support",
    why = "Two Eldritch Blasts a turn (Quickened from Sorcerer 3), Charisma added twice per beam (Agonising Blast + Potent Robe), Hexblade's Curse uses the bonus actions Sorcery Points cannot fill, Action Surge at 12. About 20% more sustained damage than the Fiend Sorlock and 50-65% more in the opening round.",
    classes = { "Sorcerer", "Warlock", "Fighter" }, start = "Sorcerer",
    races = { "Human" },
    raceWhy = "Wyll's race is locked. Human Civil Militia gives shield proficiency, so the caster can carry a shield.",
    background = "Wyll's own background (locked)", bg = "Folk Hero",
    raceHl = { "Perception" },
    base = { STR = 8, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 15 }, plus2 = "CHA", plus1 = "CON",
    skills = { "Deception", "Intimidation", "Perception" },
    levels = {
      L("Sorcerer", { "Draconic Bloodline, Draconic Ancestry: Red (Fire)", "Cantrips: Fire Bolt, Shocking Grasp, Mage Hand, Minor Illusion", "Spells: Shield, Magic Missile", "Skills: Deception, Intimidation (Human Versatility: Perception)" },
        { "Draconic Bloodline", "Draconic Ancestry: Red (Fire)", "Fire Bolt", "Shocking Grasp", "Mage Hand", "Minor Illusion", "Shield", "Magic Missile", "Deception", "Intimidation" }),
      L("Warlock", { "Patron: The Hexblade (Hex Warrior, Hexblade's Curse)", "Cantrips: Eldritch Blast, Toll the Dead", "Spells: Hex, Armour of Agathys" },
        { "The Hexblade", "Eldritch Blast", "Toll the Dead", "Hex", "Armour of Agathys" }),
      L("Warlock", { "Invocations: Agonising Blast, Repelling Blast", "Spell: Hellish Rebuke" },
        { "Agonising Blast", "Repelling Blast", "Hellish Rebuke" }),
      L("Sorcerer", { "Metamagic: Twinned Spell, Distant Spell (Quickened is not offered at Sorcerer 2)", "Spell: Sleep" },
        { "Metamagic: Twinned Spell", "Metamagic: Distant Spell", "Sleep" }),
      L("Sorcerer", { "Metamagic: Quickened Spell (Quickened Eldritch Blast as the bonus action)", "Spell: Hold Person (twin it)", "Eldritch Blast now fires 2 beams" },
        { "Metamagic: Quickened Spell", "Hold Person" }),
      L("Sorcerer", { "Feat: Ability Improvement +2 CHA", "Cantrip: Light", "Spell: Misty Step" },
        { "Ability Improvement", "Light", "Misty Step" }, { asi = { CHA = 2 } }),
      L("Sorcerer", { "Spell: Haste" }, { "Haste" }),
      L("Sorcerer", { "Elemental Affinity (fire spells add CHA)", "Spell: Fireball" }, { "Fireball" }),
      L("Sorcerer", { "Spell: Greater Invisibility (advantage when the Risky Ring is on someone else)" }, { "Greater Invisibility" }),
      L("Sorcerer", { "Feat: Ability Improvement +1 CHA +1 CON (CHA 22 with Birthright; Spell Sniper instead if Auntie Ethel's Hair or the Mirror of Loss already gave +CHA)", "Spell: Dimension Door", "Eldritch Blast now fires 3 beams" },
        { "Ability Improvement", "Dimension Door" }, { asi = { CHA = 1, CON = 1 } }),
      L("Fighter", { "Fighting Style: Protection (works with the shield)", "Second Wind", "Alternative: Sorcerer 9, Hold Monster" }, { "Protection" }),
      L("Fighter", { "Action Surge (a third Eldritch Blast once per short rest)", "Alternative: Sorcerer 10, Metamagic: Heightened Spell" }, {}),
    },
    gear = "Potent Robe, Birthright, Markoheshkir, Ketheric's Shield, Helldusk Gloves (or Spellmight Gloves), Cloak of the Weave, Callous Glow Ring, Risky Ring, The Dead Shot in the ranged slot",
    note = "Respec Wyll with Withers and start as Sorcerer (CON saves for Hex). Levels 1-10 are a plain Hexblade Sorlock; at 11-12 take Fighter 1-2 for Action Surge, or Sorcerer 9-10 for Hold Monster and Heightened Spell (5% less damage, better control). In the story his patron stays Mizora whatever subclass you pick.",
  },
  {
    id = "evoker", name = "Evocation Wizard 12", tier = "A",
    role = "Blaster/control; Sculpt Spells means no friendly fire",
    why = "Biggest spell list, Empowered Evocation adds INT to damage.",
    classes = { "Wizard" }, start = "Wizard",
    races = { "Githyanki", "High Elf", "Rock Gnome" },
    raceWhy = "Githyanki: medium armour + Misty Step. High Elf: extra cantrip.",
    background = "Sage (Arcana, History)", bg = "Sage",
    base = { STR = 8, DEX = 14, CON = 15, INT = 15, WIS = 10, CHA = 8 }, plus2 = "INT", plus1 = "CON",
    skills = { "Arcana", "History", "Investigation", "Insight" },
    levels = {
      L("Wizard", { "Cantrips: Fire Bolt, Ray of Frost, Minor Illusion", "Spells: Magic Missile, Shield, Find Familiar, Chromatic Orb, Sleep, Feather Fall", "Skills: Investigation, Insight" }, { "Fire Bolt", "Ray of Frost", "Minor Illusion", "Magic Missile", "Shield", "Find Familiar", "Chromatic Orb", "Sleep", "Feather Fall", "Investigation", "Insight" }),
      L("Wizard", { "Evocation School", "Spells: Mage Armour, Thunderwave" }, { "Evocation", "Mage Armour", "Thunderwave" }),
      L("Wizard", { "Spells: Misty Step, Scorching Ray" }, { "Misty Step", "Scorching Ray" }),
      L("Wizard", { "Feat: Ability Improvement +2 INT", "Cantrip: Shocking Grasp", "Spells: Hold Person, Shatter" }, { "Ability Improvement", "Shocking Grasp", "Hold Person", "Shatter" }, { asi = { INT = 2 } }),
      L("Wizard", { "Spells: Fireball, Counterspell" }, { "Fireball", "Counterspell" }),
      L("Wizard", { "Potent Cantrip", "Spells: Haste, Lightning Bolt" }, { "Haste", "Lightning Bolt" }),
      L("Wizard", { "Spells: Greater Invisibility, Ice Storm" }, { "Greater Invisibility", "Ice Storm" }),
      L("Wizard", { "Feat: War Caster (or Alert)", "Spells: Wall of Fire, Banishment" }, { "War Caster", "Wall of Fire", "Banishment" }),
      L("Wizard", { "Spells: Cone of Cold, Hold Monster" }, { "Cone of Cold", "Hold Monster" }),
      L("Wizard", { "Empowered Evocation", "Cantrip: Mage Hand", "Spells: Telekinesis, Conjure Elemental" }, { "Mage Hand", "Telekinesis", "Conjure Elemental" }),
      L("Wizard", { "Spells: Chain Lightning, Disintegrate" }, { "Chain Lightning", "Disintegrate" }),
      L("Wizard", { "Feat: Ability Improvement +1 INT +1 CON (INT 20)", "Spells: Globe of Invulnerability, Otiluke's Freezing Sphere" }, { "Ability Improvement", "Globe of Invulnerability", "Otiluke's Freezing Sphere" }, { asi = { INT = 1, CON = 1 } }),
    },
    gear = "Markoheshkir, Robe of Supreme Defences, Ring of Feywild Sparks / Ring of Spiteful Thunder, Hat of Fire Acuity / Lightning gear set",
  },
  ---------------------------------------------------------------- DRUID
  {
    id = "moondruid", name = "Circle of the Moon Druid 12", tier = "A",
    role = "Shapeshifting tank (Owlbear -> Myrmidons) + healing",
    why = "Combat Wild Shape as a bonus action gives a huge second HP bar; Myrmidons at 10 are top-tier.",
    classes = { "Druid" }, start = "Druid",
    races = { "Wood Elf", "Wood Half-Elf", "Shield Dwarf" },
    raceWhy = "Wildshape uses beast stats - pick mobility/utility.",
    background = "Outlander (Athletics, Survival)", bg = "Outlander",
    base = { STR = 10, DEX = 14, CON = 15, INT = 8, WIS = 15, CHA = 8 }, plus2 = "WIS", plus1 = "CON",
    skills = { "Athletics", "Survival", "Perception", "Nature" },
    levels = {
      L("Druid", { "Cantrips: Guidance, Thorn Whip", "Skills: Perception, Nature", "Prepare: Healing Word, Entangle, Thunderwave" }, { "Guidance", "Thorn Whip", "Perception", "Nature", "Healing Word", "Entangle", "Thunderwave" }),
      L("Druid", { "Circle of the Moon" }, { "Circle of the Moon" }),
      L("Druid", { "Prepare: Moonbeam, Spike Growth" }, { "Moonbeam", "Spike Growth" }),
      L("Druid", { "Feat: Ability Improvement +2 WIS", "Cantrip: Produce Flame", "Wild Shape: Owlbear" }, { "Ability Improvement", "Produce Flame" }, { asi = { WIS = 2 } }),
      L("Druid", { "Prepare: Call Lightning, Plant Growth" }, { "Call Lightning", "Plant Growth" }),
      L("Druid", { "Primal Strike; Wild Shape: Dire Raven/Sabre-Toothed Tiger" }, {}),
      L("Druid", { "Prepare: Polymorph, Wall of Fire" }, { "Polymorph", "Wall of Fire" }),
      L("Druid", { "Feat: Alert (or Tough)" }, { "Alert" }),
      L("Druid", { "Prepare: Insect Plague, Conjure Elemental" }, { "Insect Plague", "Conjure Elemental" }),
      L("Druid", { "Wild Shape: Myrmidons", "Cantrip: Resistance" }, { "Resistance" }),
      L("Druid", { "Prepare: Heal, Sunbeam" }, { "Heal", "Sunbeam" }),
      L("Druid", { "Feat: Ability Improvement +1 WIS +1 CON" }, { "Ability Improvement" }, { asi = { WIS = 1, CON = 1 } }),
    },
    gear = "Gear stays on in Wild Shape: prioritise on-hit and resistance items",
  },
  {
    id = "starsdruid", name = "Circle of Stars Druid 12", tier = "A",
    role = "Caster/healer with free bonus-action attacks (Archer) or heal boost (Chalice)",
    why = "Patch 8 subclass; Starry Form keeps concentration safe (Dragon) and adds damage/heals every turn.",
    classes = { "Druid" }, start = "Druid",
    races = { "Wood Half-Elf", "Githyanki", "Shield Dwarf" },
    raceWhy = "Dwarf/Githyanki for medium armour + shields.",
    background = "Sage (Arcana, History)", bg = "Sage",
    base = { STR = 8, DEX = 14, CON = 15, INT = 8, WIS = 15, CHA = 10 }, plus2 = "WIS", plus1 = "CON",
    skills = { "Arcana", "History", "Perception", "Insight" },
    levels = {
      L("Druid", { "Cantrips: Guidance, Produce Flame", "Skills: Perception, Insight", "Prepare: Healing Word, Faerie Fire, Thunderwave" }, { "Guidance", "Produce Flame", "Perception", "Insight", "Healing Word", "Faerie Fire", "Thunderwave" }),
      L("Druid", { "Circle of the Stars (Starry Form: Archer/Chalice/Dragon)" }, { "Circle of the Stars" }),
      L("Druid", { "Prepare: Moonbeam, Spike Growth" }, { "Moonbeam", "Spike Growth" }),
      L("Druid", { "Feat: Ability Improvement +2 WIS", "Cantrip: Resistance" }, { "Ability Improvement", "Resistance" }, { asi = { WIS = 2 } }),
      L("Druid", { "Prepare: Call Lightning, Sleet Storm" }, { "Call Lightning", "Sleet Storm" }),
      L("Druid", { "Cosmic Omen" }, {}),
      L("Druid", { "Prepare: Polymorph, Wall of Fire" }, { "Polymorph", "Wall of Fire" }),
      L("Druid", { "Feat: War Caster" }, { "War Caster" }),
      L("Druid", { "Prepare: Insect Plague, Mass Cure Wounds" }, { "Insect Plague", "Mass Cure Wounds" }),
      L("Druid", { "Twinkling Constellations", "Cantrip: Thorn Whip" }, { "Thorn Whip" }),
      L("Druid", { "Prepare: Heal, Sunbeam" }, { "Heal", "Sunbeam" }),
      L("Druid", { "Feat: Alert" }, { "Alert" }),
    },
    gear = "Staff of Spellpower, Amulet of Greater Health, Healing/Radiant gear for Chalice",
  },
}

BA.BuildById = {}
for _, b in ipairs(BA.Builds) do BA.BuildById[b.id] = b end

-- Origin characters: race is locked, class can be changed in character creation or via Withers.
-- Keys are the Origin resource Name, lower-cased with punctuation removed.
BA.Origins = {
  astarion    = { builds = { "thx", "gloomassassin" }, note = "High Elf (locked). Default Rogue - respec to Ranger start (Withers). Hand-crossbow Thief version first; longbow Assassin as the alternative." },
  gale        = { builds = { "tempestevoker", "stormsorc" }, note = "Human (locked). Wizard 1-5, Tempest Cleric at 6-7, then Wizard to 10." },
  karlach     = { builds = { "giants", "throwzerker", "throw_zerk7_thief3" }, note = "Zariel Tiefling (locked). Barbarian is already her best class; the Berserker / Thief thrower is the third option." },
  laezel      = { builds = { "bmgiant", "sorcadin" }, note = "Githyanki (locked). Stays Fighter: Battle Master with an advantage source, or respec to Sorcadin." },
  shadowheart = { builds = { "lightcleric", "lightquick" }, note = "High Half-Elf (locked). Pick Light Domain when choosing her domain. Same build on the Shar and Selune paths." },
  wyll        = { builds = { "sorlock", "lockadin", "hexsorlock" }, note = "Human (locked). Patch 8 Hexblade makes Lockadin and the Hexblade Sorlock strong alternatives." },
  halsin      = { builds = { "moondruid", "tbmonk" }, note = "Wood Elf (locked). Moon Druid, or respec to Tavern Brawler Monk." },
  jaheira     = { builds = { "starsdruid", "gloomassassin" }, note = "High Half-Elf (locked)." },
  minsc       = { builds = { "gloomassassin", "battlemaster" }, note = "Human (locked)." },
  minthara    = { builds = { "sorcadin", "oathbreaker" }, note = "Drow (locked). Paladin builds suit her perfectly." },
  darkurge    = { builds = { "throw_zerk5_thief4", "throwzerker" }, note = "The Dark Urge: race and class are free. The Berserker / Thief / Champion thrower is the strongest; builds for the class you pick follow." },
  generic     = { builds = {}, note = "Custom Tav." },
}
